// src/pages/PrintingConfigPage.jsx
import React, { useState, useEffect } from 'react';
import {
  Printer, RefreshCw, CheckCircle, AlertCircle, Download,
  Play, Trash2, Cpu, FileText, Check, UtensilsCrossed,
  Receipt, DollarSign, Settings, ShieldCheck, Sparkles, ExternalLink
} from 'lucide-react';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Select, Input } from '../components/ui/Input';
import { Badge } from '../components/ui/Badge';
import { api } from '../api/client';
import { useUiStore } from '../store/uiStore';
import {
  checkPrintBridgeHealth,
  getPrintBridgePrinters,
  sendTestPrint,
  sendToThermalBridge
} from '../utils/printUtils';

export const PrintingConfigPage = () => {
  const addToast = useUiStore((state) => state.addToast);

  // Estados del Formulario / Settings
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [settings, setSettings] = useState({});

  // Parámetros de Impresión
  const [enableSilentPrinting, setEnableSilentPrinting] = useState(true);
  const [autoPrintKitchenTickets, setAutoPrintKitchenTickets] = useState(true);
  const [autoPrintInvoices, setAutoPrintInvoices] = useState(false);
  const [printerKitchenName, setPrinterKitchenName] = useState('');
  const [printerReceiptName, setPrinterReceiptName] = useState('');
  const [printerBarName, setPrinterBarName] = useState('');
  const [paperWidth, setPaperWidth] = useState('80mm');
  const [openDrawerOnPayment, setOpenDrawerOnPayment] = useState(true);
  const [bridgeUrl, setBridgeUrl] = useState('http://localhost:8088');

  // Estado en vivo del Bridge
  const [bridgeStatus, setBridgeStatus] = useState('checking'); // 'online' | 'offline' | 'checking'
  const [bridgeInfo, setBridgeInfo] = useState(null);
  const [detectedPrinters, setDetectedPrinters] = useState([]);
  const [testingKitchen, setTestingKitchen] = useState(false);
  const [testingReceipt, setTestingReceipt] = useState(false);
  const [testingDrawer, setTestingDrawer] = useState(false);

  // 1. Cargar Settings desde Backend
  const loadSettings = async () => {
    setLoading(true);
    try {
      const data = await api.get('/settings');
      setSettings(data);
      setEnableSilentPrinting(data.enable_silent_printing !== undefined ? !!data.enable_silent_printing : true);
      setAutoPrintKitchenTickets(data.auto_print_kitchen_tickets !== undefined ? !!data.auto_print_kitchen_tickets : true);
      setAutoPrintInvoices(!!data.auto_print_invoices);
      setPrinterKitchenName(data.printer_kitchen_name || '');
      setPrinterReceiptName(data.printer_receipt_name || '');
      setPrinterBarName(data.printer_bar_name || '');
      setPaperWidth(data.paper_width || '80mm');
      setOpenDrawerOnPayment(data.open_drawer_on_payment !== undefined ? !!data.open_drawer_on_payment : true);
      setBridgeUrl(data.silent_print_bridge_url || 'http://localhost:8088');
    } catch (err) {
      addToast('Error al cargar configuración de impresión: ' + err.message, 'danger');
    } finally {
      setLoading(false);
    }
  };

  // 2. Probar conexión en vivo con el Bridge de Node.js
  const testBridgeConnection = async () => {
    setBridgeStatus('checking');
    try {
      const health = await checkPrintBridgeHealth(bridgeUrl);
      if (health && health.online) {
        setBridgeStatus('online');
        setBridgeInfo(health.data);
        const printers = await getPrintBridgePrinters(bridgeUrl);
        setDetectedPrinters(printers);
        addToast('Print Bridge Node.js conectado correctamente', 'success');
      } else {
        setBridgeStatus('offline');
        setBridgeInfo(null);
        setDetectedPrinters([]);
      }
    } catch (e) {
      setBridgeStatus('offline');
      setBridgeInfo(null);
      setDetectedPrinters([]);
    }
  };

  useEffect(() => {
    loadSettings();
    testBridgeConnection();
  }, []);

  // 3. Guardar Configuración
  const handleSave = async (e) => {
    if (e) e.preventDefault();
    setSaving(true);
    try {
      const payload = {
        ...settings,
        enable_silent_printing: enableSilentPrinting,
        auto_print_kitchen_tickets: autoPrintKitchenTickets,
        auto_print_invoices: autoPrintInvoices,
        printer_kitchen_name: printerKitchenName,
        printer_receipt_name: printerReceiptName,
        printer_bar_name: printerBarName,
        paper_width: paperWidth,
        open_drawer_on_payment: openDrawerOnPayment,
        silent_print_bridge_url: bridgeUrl
      };

      await api.put('/settings', payload);
      setSettings(payload);
      addToast('Configuración de impresión guardada correctamente', 'success');
    } catch (err) {
      addToast('Error al guardar configuración: ' + err.message, 'danger');
    } finally {
      setSaving(false);
    }
  };

  // 4. Pruebas de Impresión
  const handleTestKitchen = async () => {
    setTestingKitchen(true);
    try {
      const res = await sendTestPrint(printerKitchenName, 'cocina', bridgeUrl);
      if (res && res.success) {
        addToast('Ticket de prueba enviado a la impresora de Cocina', 'success');
      } else {
        addToast('No se pudo enviar a la impresora de Cocina. Verifica que el Print Bridge esté activo.', 'warning');
      }
    } catch (e) {
      addToast('Error al enviar prueba: ' + e.message, 'danger');
    } finally {
      setTestingKitchen(false);
    }
  };

  const handleTestReceipt = async () => {
    setTestingReceipt(true);
    try {
      const res = await sendTestPrint(printerReceiptName, 'caja', bridgeUrl);
      if (res && res.success) {
        addToast('Factura de prueba enviada a la impresora de Caja', 'success');
      } else {
        addToast('No se pudo enviar a la impresora de Caja. Verifica que el Print Bridge esté activo.', 'warning');
      }
    } catch (e) {
      addToast('Error al enviar prueba: ' + e.message, 'danger');
    } finally {
      setTestingReceipt(false);
    }
  };

  const handleTestDrawer = async () => {
    setTestingDrawer(true);
    try {
      const res = await sendToThermalBridge('', printerReceiptName, bridgeUrl);
      if (res && res.success) {
        addToast('Señal de apertura enviada a la gaveta de dinero', 'info');
      } else {
        addToast('Verifica que la gaveta esté conectada al puerto RJ11 de la impresora de Caja', 'warning');
      }
    } catch (e) {
      addToast('Error al probar gaveta: ' + e.message, 'danger');
    } finally {
      setTestingDrawer(false);
    }
  };

  // 5. Descargas de Scripts
  const downloadNodeInstaller = () => {
    window.open('https://nodejs.org/dist/v20.18.0/node-v20.18.0-x64.msi', '_blank');
    addToast('Descargando instalador oficial de Node.js LTS (64 bits)...', 'info');
  };

  const downloadStarterBat = () => {
    const batContent = `@echo off\r
title KAMIA POS - Print Bridge Node.js\r
color 0A\r
cls\r
echo ======================================================================\r
echo           KAMIA POS - SERVIDOR DE IMPRESION DIRECTA (NODE.JS)\r
echo ======================================================================\r
echo.\r
where node >nul 2>nul\r
if %errorlevel% neq 0 (\r
    color 0C\r
    echo [ALERTA] Node.js no esta instalado en este computador.\r
    echo Node.js es OBLIGATORIO para el Print Bridge.\r
    echo.\r
    echo Abriendo instalador oficial de Node.js...\r
    start https://nodejs.org/dist/v20.18.0/node-v20.18.0-x64.msi\r
    pause\r
    exit /b 1\r
)\r
for /f "tokens=*" %%i in ('node -v') do set NODE_VERSION=%%i\r
echo [OK] Node.js detectado: %NODE_VERSION%\r
set "TARGET_DIR=%LOCALAPPDATA%\\GastrosPOS\\PrintBridge"\r
if not exist "%TARGET_DIR%" mkdir "%TARGET_DIR%"\r
set "BRIDGE_FILE=%TARGET_DIR%\\bridge.js"\r
if exist "%~dp0bridge.js" (\r
    copy /y "%~dp0bridge.js" "%BRIDGE_FILE%" >nul\r
) else (\r
    powershell -NoProfile -ExecutionPolicy Bypass -Command "[System.IO.File]::WriteAllBytes('$env:LOCALAPPDATA\\GastrosPOS\\PrintBridge\\bridge.js', [System.Convert]::FromBase64String('LyoqCiAqIEtBTUlBIGJ5IEpGIOKAlCBOb2RlLmpzIFRoZXJtYWwgUHJpbnQgQnJpZGdlIHYyLjAKICogU2Vydmlkb3IgSFRUUCBsb2NhbCBwYXJhIGltcHJlc2nDs24gdMOpcm1pY2Egc2lsZW5jaW9zYSBkaXJlY3RhIChFU0MvUE9TKQogKiBQdWVydG8gcG9yIGRlZmVjdG86IDgwODgKICovCgpjb25zdCBodHRwID0gcmVxdWlyZSgnaHR0cCcpOwpjb25zdCBmcyA9IHJlcXVpcmUoJ2ZzJyk7CmNvbnN0IHBhdGggPSByZXF1aXJlKCdwYXRoJyk7CmNvbnN0IG9zID0gcmVxdWlyZSgnb3MnKTsKY29uc3QgeyBleGVjLCBleGVjRmlsZSB9ID0gcmVxdWlyZSgnY2hpbGRfcHJvY2VzcycpOwpjb25zdCBuZXQgPSByZXF1aXJlKCduZXQnKTsKCmNvbnN0IFBPUlQgPSBwcm9jZXNzLmVudi5QT1JUIHx8IDgwODg7CmNvbnN0IEhPU1QgPSAnMC4wLjAuMCc7CgovLyBDb21hbmRvcyBFU0MvUE9TIGVzdMOhbmRhcgpjb25zdCBFU0MgPSAnXHgxQic7CmNvbnN0IEdTID0gJ1x4MUQnOwpjb25zdCBFU0NfSU5JVCA9IGAke0VTQ31AYDsgICAgICAgICAgICAgICAvLyBJbmljaWFsaXphciBpbXByZXNvcmEKY29uc3QgRVNDX0NVVF9GVUxMID0gYCR7R1N9Vlx4MDBgOyAgICAgICAgLy8gQ29ydGUgdG90YWwKY29uc3QgRVNDX0NVVF9QQVJUSUFMID0gYCR7R1N9Vlx4MDFgOyAgICAgLy8gQ29ydGUgcGFyY2lhbApjb25zdCBFU0NfRFJBV0VSID0gYCR7RVNDfXBceDAwXHgxOVx4RkFgOyAvLyBBYnJpciBnYXZldGEgLyBjYWrDs24gbW9uZWRlcm8KY29uc3QgRVNDX0FMSUdOX0xFRlQgPSBgJHtFU0N9YVx4MDBgOwpjb25zdCBFU0NfQUxJR05fQ0VOVEVSID0gYCR7RVNDfWFceDAxYDsKY29uc3QgRVNDX0FMSUdOX1JJR0hUID0gYCR7RVNDfWFceDAyYDsKY29uc3QgRVNDX0JPTERfT04gPSBgJHtFU0N9RVx4MDFgOwpjb25zdCBFU0NfQk9MRF9PRkYgPSBgJHtFU0N9RVx4MDBgOwoKLyoqCiAqIE9idGVuZXIgbGlzdGEgZGUgaW1wcmVzb3JhcyBkZSBXaW5kb3dzIHVzYW5kbyBQb3dlclNoZWxsCiAqLwpmdW5jdGlvbiBnZXRXaW5kb3dzUHJpbnRlcnMoKSB7CiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiB7CiAgICBjb25zdCBwc0NtZCA9IGBHZXQtQ2ltSW5zdGFuY2UgV2luMzJfUHJpbnRlciB8IFNlbGVjdC1PYmplY3QgTmFtZSwgRGVmYXVsdCwgUG9ydE5hbWUsIERyaXZlck5hbWUsIFByaW50ZXJTdGF0dXMgfCBDb252ZXJ0VG8tSnNvbiAtQ29tcHJlc3NgOwogICAgZXhlY0ZpbGUoJ3Bvd2Vyc2hlbGwnLCBbJy1Ob1Byb2ZpbGUnLCAnLUV4ZWN1dGlvblBvbGljeScsICdCeXBhc3MnLCAnLUNvbW1hbmQnLCBwc0NtZF0sIHsgd2luZG93c0hpZGU6IHRydWUsIHRpbWVvdXQ6IDYwMDAgfSwgKGVyciwgc3Rkb3V0KSA9PiB7CiAgICAgIGlmIChlcnIgfHwgIXN0ZG91dC50cmltKCkpIHsKICAgICAgICAvLyBGYWxsYmFjayByw6FwaWRvIHVzYW5kbyB3bWljCiAgICAgICAgZXhlYygnd21pYyBwcmludGVyIGdldCBuYW1lLGRlZmF1bHQgL2Zvcm1hdDpjc3YnLCB7IHdpbmRvd3NIaWRlOiB0cnVlLCB0aW1lb3V0OiA0MDAwIH0sICh3bWljRXJyLCB3bWljT3V0KSA9PiB7CiAgICAgICAgICBpZiAod21pY0VyciB8fCAhd21pY091dCkgewogICAgICAgICAgICByZXR1cm4gcmVzb2x2ZShbeyBuYW1lOiAnSW1wcmVzb3JhIFByZWRldGVybWluYWRhIGRlIFdpbmRvd3MnLCBpc0RlZmF1bHQ6IHRydWUsIHBvcnQ6ICdERUZBVUxUJyB9XSk7CiAgICAgICAgICB9CiAgICAgICAgICBjb25zdCBsaW5lcyA9IHdtaWNPdXQuc3BsaXQoJ1xuJykubWFwKGwgPT4gbC50cmltKCkpLmZpbHRlcihCb29sZWFuKS5zbGljZSgxKTsKICAgICAgICAgIGNvbnN0IHByaW50ZXJzID0gbGluZXMubWFwKGxpbmUgPT4gewogICAgICAgICAgICBjb25zdCBwYXJ0cyA9IGxpbmUuc3BsaXQoJywnKTsKICAgICAgICAgICAgaWYgKHBhcnRzLmxlbmd0aCA+PSAzKSB7CiAgICAgICAgICAgICAgcmV0dXJuIHsgbmFtZTogcGFydHNbMl0udHJpbSgpLCBpc0RlZmF1bHQ6IHBhcnRzWzFdLnRyaW0oKS50b0xvd2VyQ2FzZSgpID09PSAndHJ1ZScsIHBvcnQ6ICdVU0IvTFBUJyB9OwogICAgICAgICAgICB9CiAgICAgICAgICAgIHJldHVybiBudWxsOwogICAgICAgICAgfSkuZmlsdGVyKEJvb2xlYW4pOwogICAgICAgICAgcmVzb2x2ZShwcmludGVycy5sZW5ndGggPiAwID8gcHJpbnRlcnMgOiBbeyBuYW1lOiAnSW1wcmVzb3JhIFByZWRldGVybWluYWRhIGRlIFdpbmRvd3MnLCBpc0RlZmF1bHQ6IHRydWUsIHBvcnQ6ICdERUZBVUxUJyB9XSk7CiAgICAgICAgfSk7CiAgICAgICAgcmV0dXJuOwogICAgICB9CgogICAgICB0cnkgewogICAgICAgIGxldCBkYXRhID0gSlNPTi5wYXJzZShzdGRvdXQpOwogICAgICAgIGlmICghQXJyYXkuaXNBcnJheShkYXRhKSkgZGF0YSA9IFtkYXRhXTsKICAgICAgICBjb25zdCBwcmludGVycyA9IGRhdGEubWFwKHAgPT4gKHsKICAgICAgICAgIG5hbWU6IHAuTmFtZSB8fCAnSW1wcmVzb3JhJywKICAgICAgICAgIGlzRGVmYXVsdDogQm9vbGVhbihwLkRlZmF1bHQpLAogICAgICAgICAgcG9ydDogcC5Qb3J0TmFtZSB8fCAnJywKICAgICAgICAgIGRyaXZlcjogcC5Ecml2ZXJOYW1lIHx8ICcnLAogICAgICAgICAgc3RhdHVzOiBwLlByaW50ZXJTdGF0dXMgfHwgMwogICAgICAgIH0pKTsKICAgICAgICByZXNvbHZlKHByaW50ZXJzKTsKICAgICAgfSBjYXRjaCAocGFyc2VFcnIpIHsKICAgICAgICByZXNvbHZlKFt7IG5hbWU6ICdJbXByZXNvcmEgUHJlZGV0ZXJtaW5hZGEgZGUgV2luZG93cycsIGlzRGVmYXVsdDogdHJ1ZSwgcG9ydDogJ0RFRkFVTFQnIH1dKTsKICAgICAgfQogICAgfSk7CiAgfSk7Cn0KCi8qKgogKiBJbXByaW1pciBSQVcgZW4gaW1wcmVzb3JhIGRlIHJlZCAoVENQIFNvY2tldCBwdWVydG8gOTEwMCkKICovCmZ1bmN0aW9uIHByaW50TmV0d29ya1NvY2tldChpcCwgcG9ydCA9IDkxMDAsIGJ1ZmZlcikgewogIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7CiAgICBjb25zdCBjbGllbnQgPSBuZXcgbmV0LlNvY2tldCgpOwogICAgY2xpZW50LnNldFRpbWVvdXQoNTAwMCk7CiAgICBjbGllbnQuY29ubmVjdChwb3J0LCBpcCwgKCkgPT4gewogICAgICBjbGllbnQud3JpdGUoYnVmZmVyLCAoKSA9PiB7CiAgICAgICAgY2xpZW50LmVuZCgpOwogICAgICAgIHJlc29sdmUodHJ1ZSk7CiAgICAgIH0pOwogICAgfSk7CiAgICBjbGllbnQub24oJ2Vycm9yJywgKGVycikgPT4gcmVqZWN0KGVycikpOwogICAgY2xpZW50Lm9uKCd0aW1lb3V0JywgKCkgPT4gewogICAgICBjbGllbnQuZGVzdHJveSgpOwogICAgICByZWplY3QobmV3IEVycm9yKGBUaW1lb3V0IGRlIGNvbmV4acOzbiBhIGxhIGltcHJlc29yYSBlbiAke2lwfToke3BvcnR9YCkpOwogICAgfSk7CiAgfSk7Cn0KCi8qKgogKiBJbXByaW1pciBlbiBpbXByZXNvcmEgbG9jYWwvY29tcGFydGlkYSBkZSBXaW5kb3dzCiAqLwpmdW5jdGlvbiBwcmludFdpbmRvd3NTcG9vbGVyKHByaW50ZXJOYW1lLCBidWZmZXIpIHsKICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4gewogICAgY29uc3QgdGVtcEZpbGUgPSBwYXRoLmpvaW4ob3MudG1wZGlyKCksIGBrYW1pYV9wcmludF8ke0RhdGUubm93KCl9XyR7TWF0aC5yYW5kb20oKS50b1N0cmluZygzNikuc3Vic3RyKDIsIDYpfS5iaW5gKTsKICAgIAogICAgZnMud3JpdGVGaWxlKHRlbXBGaWxlLCBidWZmZXIsICh3cml0ZUVycikgPT4gewogICAgICBpZiAod3JpdGVFcnIpIHJldHVybiByZWplY3Qod3JpdGVFcnIpOwoKICAgICAgLy8gVXNhciBzY3JpcHQgUG93ZXJTaGVsbCBlbWJlYmlkbyBwYXJhIGVudmlhciBsb3MgYnl0ZXMgUkFXIGFsIHNwb29sZXIgZGUgbGEgaW1wcmVzb3JhCiAgICAgIGNvbnN0IHRhcmdldFByaW50ZXIgPSBwcmludGVyTmFtZSAmJiBwcmludGVyTmFtZSAhPT0gJ0ltcHJlc29yYSBQcmVkZXRlcm1pbmFkYSBkZSBXaW5kb3dzJwogICAgICAgID8gcHJpbnRlck5hbWUucmVwbGFjZSgvJy9nLCAiJyciKQogICAgICAgIDogJyc7CgogICAgICBjb25zdCBwc1NjcmlwdCA9IGAKJHRlbXBGaWxlID0gJyR7dGVtcEZpbGUucmVwbGFjZSgvJy9nLCAiJyciKX0nOwokcHJpbnRlck5hbWUgPSAnJHt0YXJnZXRQcmludGVyfSc7CgppZiAoLW5vdCAkcHJpbnRlck5hbWUpIHsKICAkZGVmYXVsdFByaW50ZXIgPSBHZXQtQ2ltSW5zdGFuY2UgV2luMzJfUHJpbnRlciB8IFdoZXJlLU9iamVjdCB7ICRfLkRlZmF1bHQgLWVxICR0cnVlIH0gfCBTZWxlY3QtT2JqZWN0IC1GaXJzdCAxOwogIGlmICgkZGVmYXVsdFByaW50ZXIpIHsgJHByaW50ZXJOYW1lID0gJGRlZmF1bHRQcmludGVyLk5hbWUgfQogIGVsc2UgewogICAgJGFueVByaW50ZXIgPSBHZXQtQ2ltSW5zdGFuY2UgV2luMzJfUHJpbnRlciB8IFNlbGVjdC1PYmplY3QgLUZpcnN0IDE7CiAgICBpZiAoJGFueVByaW50ZXIpIHsgJHByaW50ZXJOYW1lID0gJGFueVByaW50ZXIuTmFtZSB9CiAgfQp9CgppZiAoLW5vdCAkcHJpbnRlck5hbWUpIHsKICBleGl0IDEKfQoKIyBFbnZpYXIgYWwgc3Bvb2xlcgp0cnkgewogIEdldC1Db250ZW50IC1QYXRoICR0ZW1wRmlsZSAtRW5jb2RpbmcgRGVmYXVsdCB8IE91dC1QcmludGVyIC1OYW1lICRwcmludGVyTmFtZSAtRXJyb3JBY3Rpb24gU3RvcAogIGV4aXQgMAp9IGNhdGNoIHsKICB0cnkgewogICAgW1N5c3RlbS5JTy5GaWxlXTo6UmVhZEFsbFRleHQoJHRlbXBGaWxlKSB8IE91dC1QcmludGVyIC1OYW1lICRwcmludGVyTmFtZSAtRXJyb3JBY3Rpb24gU3RvcAogICAgZXhpdCAwCiAgfSBjYXRjaCB7CiAgICBXcml0ZS1FcnJvciAkXy5FeGNlcHRpb24uTWVzc2FnZQogICAgZXhpdCAxCiAgfQp9CiAgICAgIGAudHJpbSgpOwoKICAgICAgZXhlY0ZpbGUoJ3Bvd2Vyc2hlbGwnLCBbJy1Ob1Byb2ZpbGUnLCAnLUV4ZWN1dGlvblBvbGljeScsICdCeXBhc3MnLCAnLUNvbW1hbmQnLCBwc1NjcmlwdF0sIHsgd2luZG93c0hpZGU6IHRydWUsIHRpbWVvdXQ6IDgwMDAgfSwgKHBzRXJyKSA9PiB7CiAgICAgICAgLy8gTGltcGlhciBhcmNoaXZvIHRlbXBvcmFsCiAgICAgICAgdHJ5IHsgZnMudW5saW5rU3luYyh0ZW1wRmlsZSk7IH0gY2F0Y2ggKGUpIHt9CgogICAgICAgIGlmIChwc0VycikgewogICAgICAgICAgY29uc29sZS5lcnJvcihgW1ByaW50QnJpZGdlXSBFcnJvciBhbCBlbnZpYXIgYSBzcG9vbGVyICgke3ByaW50ZXJOYW1lIHx8ICdEZWZhdWx0J30pOmAsIHBzRXJyLm1lc3NhZ2UpOwogICAgICAgICAgcmV0dXJuIHJlamVjdChuZXcgRXJyb3IoYEVycm9yIGFsIGVudmlhciB0cmFiYWpvIGEgbGEgaW1wcmVzb3JhICR7cHJpbnRlck5hbWUgfHwgJ0RlZmF1bHQnfTogJHtwc0Vyci5tZXNzYWdlfWApKTsKICAgICAgICB9CiAgICAgICAgcmVzb2x2ZSh0cnVlKTsKICAgICAgfSk7CiAgICB9KTsKICB9KTsKfQoKLyoqCiAqIFNlcnZpZG9yIEhUVFAKICovCmNvbnN0IHNlcnZlciA9IGh0dHAuY3JlYXRlU2VydmVyKGFzeW5jIChyZXEsIHJlcykgPT4gewogIC8vIENPUlMgSGVhZGVycwogIHJlcy5zZXRIZWFkZXIoJ0FjY2Vzcy1Db250cm9sLUFsbG93LU9yaWdpbicsICcqJyk7CiAgcmVzLnNldEhlYWRlcignQWNjZXNzLUNvbnRyb2wtQWxsb3ctTWV0aG9kcycsICdHRVQsIFBPU1QsIE9QVElPTlMnKTsKICByZXMuc2V0SGVhZGVyKCdBY2Nlc3MtQ29udHJvbC1BbGxvdy1IZWFkZXJzJywgJ0NvbnRlbnQtVHlwZSwgQXV0aG9yaXphdGlvbicpOwogIHJlcy5zZXRIZWFkZXIoJ0NvbnRlbnQtVHlwZScsICdhcHBsaWNhdGlvbi9qc29uOyBjaGFyc2V0PXV0Zi04Jyk7CgogIGlmIChyZXEubWV0aG9kID09PSAnT1BUSU9OUycpIHsKICAgIHJlcy53cml0ZUhlYWQoMjAwKTsKICAgIHJldHVybiByZXMuZW5kKCk7CiAgfQoKICBjb25zdCB1cmwgPSByZXEudXJsLnNwbGl0KCc/JylbMF07CgogIC8vIDEuIEdFVCAvaGVhbHRoIG8gL3N0YXR1cwogIGlmIChyZXEubWV0aG9kID09PSAnR0VUJyAmJiAodXJsID09PSAnLycgfHwgdXJsID09PSAnL2hlYWx0aCcgfHwgdXJsID09PSAnL3N0YXR1cycpKSB7CiAgICByZXR1cm4gcmVzLmVuZChKU09OLnN0cmluZ2lmeSh7CiAgICAgIHN0YXR1czogJ29ubGluZScsCiAgICAgIHNlcnZpY2U6ICdLQU1JQSBOb2RlLmpzIFByaW50IEJyaWRnZScsCiAgICAgIHZlcnNpb246ICcyLjAuMCcsCiAgICAgIG5vZGVWZXJzaW9uOiBwcm9jZXNzLnZlcnNpb24sCiAgICAgIHBsYXRmb3JtOiBvcy5wbGF0Zm9ybSgpLAogICAgICBhcmNoOiBvcy5hcmNoKCksCiAgICAgIGhvc3RuYW1lOiBvcy5ob3N0bmFtZSgpLAogICAgICB1cHRpbWVTZWNvbmRzOiBNYXRoLmZsb29yKHByb2Nlc3MudXB0aW1lKCkpLAogICAgICB0aW1lc3RhbXA6IG5ldyBEYXRlKCkudG9JU09TdHJpbmcoKQogICAgfSkpOwogIH0KCiAgLy8gMi4gR0VUIC9wcmludGVycwogIGlmIChyZXEubWV0aG9kID09PSAnR0VUJyAmJiB1cmwgPT09ICcvcHJpbnRlcnMnKSB7CiAgICB0cnkgewogICAgICBjb25zdCBwcmludGVycyA9IGF3YWl0IGdldFdpbmRvd3NQcmludGVycygpOwogICAgICByZXR1cm4gcmVzLmVuZChKU09OLnN0cmluZ2lmeSh7IHN1Y2Nlc3M6IHRydWUsIHByaW50ZXJzIH0pKTsKICAgIH0gY2F0Y2ggKGVycikgewogICAgICByZXR1cm4gcmVzLndyaXRlSGVhZCg1MDApLmVuZChKU09OLnN0cmluZ2lmeSh7IHN1Y2Nlc3M6IGZhbHNlLCBlcnJvcjogZXJyLm1lc3NhZ2UgfSkpOwogICAgfQogIH0KCiAgLy8gMy4gUE9TVCAvcHJpbnQKICBpZiAocmVxLm1ldGhvZCA9PT0gJ1BPU1QnICYmIHVybCA9PT0gJy9wcmludCcpIHsKICAgIGxldCBib2R5ID0gJyc7CiAgICByZXEub24oJ2RhdGEnLCBjaHVuayA9PiB7IGJvZHkgKz0gY2h1bms7IH0pOwogICAgcmVxLm9uKCdlbmQnLCBhc3luYyAoKSA9PiB7CiAgICAgIHRyeSB7CiAgICAgICAgY29uc3QgcGF5bG9hZCA9IEpTT04ucGFyc2UoYm9keSB8fCAne30nKTsKICAgICAgICBjb25zdCB7IHRleHQsIHJhdywgcHJpbnRlck5hbWUsIGN1dFBhcGVyID0gdHJ1ZSwgb3BlbkRyYXdlciA9IGZhbHNlLCBpcCA9IG51bGwsIHBvcnQgPSA5MTAwIH0gPSBwYXlsb2FkOwoKICAgICAgICBpZiAoIXRleHQgJiYgIXJhdykgewogICAgICAgICAgcmV0dXJuIHJlcy53cml0ZUhlYWQoNDAwKS5lbmQoSlNPTi5zdHJpbmdpZnkoeyBzdWNjZXNzOiBmYWxzZSwgZXJyb3I6ICdFbCBjYW1wbyAidGV4dCIgbyAicmF3IiBlcyByZXF1ZXJpZG8nIH0pKTsKICAgICAgICB9CgogICAgICAgIC8vIENvbnN0cnVpciBidWZmZXIgRVNDL1BPUwogICAgICAgIGxldCBjaHVua3MgPSBbXTsKICAgICAgICBjaHVua3MucHVzaChCdWZmZXIuZnJvbShFU0NfSU5JVCwgJ2JpbmFyeScpKTsKCiAgICAgICAgaWYgKG9wZW5EcmF3ZXIpIHsKICAgICAgICAgIGNodW5rcy5wdXNoKEJ1ZmZlci5mcm9tKEVTQ19EUkFXRVIsICdiaW5hcnknKSk7CiAgICAgICAgfQoKICAgICAgICBpZiAodGV4dCkgewogICAgICAgICAgLy8gQ29kaWZpY2FyIGVuIExhdGluMS9DUDEyNTIgcGFyYSB0aWxkZXMgeSBjYXJhY3RlcmVzIGVuIGVzcGHDsW9sCiAgICAgICAgICBjaHVua3MucHVzaChCdWZmZXIuZnJvbSh0ZXh0LCAnbGF0aW4xJykpOwogICAgICAgIH0KCiAgICAgICAgaWYgKHJhdykgewogICAgICAgICAgY2h1bmtzLnB1c2goQnVmZmVyLmZyb20ocmF3LCAnYmluYXJ5JykpOwogICAgICAgIH0KCiAgICAgICAgLy8gU2FsdG9zIGRlIGzDrW5lYSB5IGNvcnRlIGRlIHBhcGVsIGF1dG9tw6F0aWNvCiAgICAgICAgaWYgKGN1dFBhcGVyICE9PSBmYWxzZSkgewogICAgICAgICAgY2h1bmtzLnB1c2goQnVmZmVyLmZyb20oJ1xuXG5cblxuJywgJ2xhdGluMScpKTsKICAgICAgICAgIGNodW5rcy5wdXNoKEJ1ZmZlci5mcm9tKEVTQ19DVVRfUEFSVElBTCwgJ2JpbmFyeScpKTsKICAgICAgICB9CgogICAgICAgIGNvbnN0IGZpbmFsQnVmZmVyID0gQnVmZmVyLmNvbmNhdChjaHVua3MpOwoKICAgICAgICAvLyBTaSBlcyBpbXByZXNvcmEgSVAgcG9yIHJlZAogICAgICAgIGlmIChpcCkgewogICAgICAgICAgYXdhaXQgcHJpbnROZXR3b3JrU29ja2V0KGlwLCBwb3J0LCBmaW5hbEJ1ZmZlcik7CiAgICAgICAgICByZXR1cm4gcmVzLmVuZChKU09OLnN0cmluZ2lmeSh7IHN1Y2Nlc3M6IHRydWUsIG1lc3NhZ2U6IGBJbXByZXNpw7NuIGVudmlhZGEgYSBzb2NrZXQgZGUgcmVkICR7aXB9OiR7cG9ydH1gIH0pKTsKICAgICAgICB9CgogICAgICAgIC8vIFNpIGVzIGltcHJlc29yYSBkZSBXaW5kb3dzIFNwb29sZXIKICAgICAgICBhd2FpdCBwcmludFdpbmRvd3NTcG9vbGVyKHByaW50ZXJOYW1lLCBmaW5hbEJ1ZmZlcik7CiAgICAgICAgcmV0dXJuIHJlcy5lbmQoSlNPTi5zdHJpbmdpZnkoeyBzdWNjZXNzOiB0cnVlLCBtZXNzYWdlOiBgVHJhYmFqbyBlbnZpYWRvIGEgbGEgY29sYSBkZSAke3ByaW50ZXJOYW1lIHx8ICdJbXByZXNvcmEgUHJlZGV0ZXJtaW5hZGEnfWAgfSkpOwoKICAgICAgfSBjYXRjaCAoZXJyKSB7CiAgICAgICAgY29uc29sZS5lcnJvcignW1ByaW50QnJpZGdlXSBFcnJvciBhbCBwcm9jZXNhciBpbXByZXNpw7NuOicsIGVycik7CiAgICAgICAgcmV0dXJuIHJlcy53cml0ZUhlYWQoNTAwKS5lbmQoSlNPTi5zdHJpbmdpZnkoeyBzdWNjZXNzOiBmYWxzZSwgZXJyb3I6IGVyci5tZXNzYWdlIH0pKTsKICAgICAgfQogICAgfSk7CiAgICByZXR1cm47CiAgfQoKICAvLyA0LiBQT1NUIC90ZXN0LXByaW50CiAgaWYgKHJlcS5tZXRob2QgPT09ICdQT1NUJyAmJiB1cmwgPT09ICcvdGVzdC1wcmludCcpIHsKICAgIGxldCBib2R5ID0gJyc7CiAgICByZXEub24oJ2RhdGEnLCBjaHVuayA9PiB7IGJvZHkgKz0gY2h1bms7IH0pOwogICAgcmVxLm9uKCdlbmQnLCBhc3luYyAoKSA9PiB7CiAgICAgIHRyeSB7CiAgICAgICAgY29uc3QgcGF5bG9hZCA9IEpTT04ucGFyc2UoYm9keSB8fCAne30nKTsKICAgICAgICBjb25zdCBwcmludGVyTmFtZSA9IHBheWxvYWQucHJpbnRlck5hbWUgfHwgbnVsbDsKICAgICAgICBjb25zdCB0ZXN0VHlwZSA9IHBheWxvYWQudHlwZSB8fCAnY29tYW5kYSc7CgogICAgICAgIGNvbnN0IG5vdyA9IG5ldyBEYXRlKCkudG9Mb2NhbGVTdHJpbmcoJ2VzLUNPJyk7CiAgICAgICAgY29uc3Qgc2VwYXJhdG9yID0gJz09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0nOwogICAgICAgIGNvbnN0IGxpbmUgPSAnLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSc7CgogICAgICAgIGxldCB0ZXN0VGV4dCA9ICcnOwogICAgICAgIHRlc3RUZXh0ICs9IGAke3NlcGFyYXRvcn1cbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYCAgICAgICAgICBLQU1JQSBQT1MgJiBFUlAgYnkgSkYgICAgICAgICBcbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYCAgICAgICJUb2RvIHR1IG5lZ29jaW8sIGNvbmVjdGFkby4iICAgICBcbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYCR7c2VwYXJhdG9yfVxuYDsKICAgICAgICB0ZXN0VGV4dCArPSBgICAgKioqIFRJQ0tFVCBERSBQUlVFQkEgREUgSU1QUkVTSU9OICoqKiBcbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYCR7bGluZX1cbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYEZlY2hhIC8gSG9yYTogICR7bm93fVxuYDsKICAgICAgICB0ZXN0VGV4dCArPSBgU2VydmljaW86ICAgICAgS0FNSUEgTm9kZS5qcyBQcmludCBCcmlkZ2UgdjIuMFxuYDsKICAgICAgICB0ZXN0VGV4dCArPSBgTW90b3I6ICAgICAgICAgTm9kZS5qcyAke3Byb2Nlc3MudmVyc2lvbn1cbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYEltcHJlc29yYTogICAgICR7cHJpbnRlck5hbWUgfHwgJ1ByZWRldGVybWluYWRhIGRlIFdpbmRvd3MnfVxuYDsKICAgICAgICB0ZXN0VGV4dCArPSBgRGVzdGlubzogICAgICAgJHt0ZXN0VHlwZSA9PT0gJ2NvY2luYScgPyAnQ29jaW5hIChDb21hbmRhKScgOiAodGVzdFR5cGUgPT09ICdjYWphJyA/ICdDYWphIChGYWN0dXJhY2nDs24pJyA6ICdHZW5lcmFsJyl9XG5gOwogICAgICAgIHRlc3RUZXh0ICs9IGAke2xpbmV9XG5gOwogICAgICAgIHRlc3RUZXh0ICs9IGBDYXJhY3RlcmVzIEVzcGVjaWFsZXMgLyBBY2VudG9zOlxuYDsKICAgICAgICB0ZXN0VGV4dCArPSBgw6Egw6kgw60gw7Mgw7ogw7Egw4Egw4kgw40gw5Mgw5ogw5EgJCAlICYgQCAjXG5gOwogICAgICAgIHRlc3RUZXh0ICs9IGAke2xpbmV9XG5gOwogICAgICAgIHRlc3RUZXh0ICs9IGBFc3RhZG86ICAgICAgICBDT05FWElPTiAxMDAlIEVYSVRPU0FcbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYEltcHJlc2lvbjogICAgIERpcmVjdGEgeSBTaWxlbmNpb3NhIChPSylcbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYCR7c2VwYXJhdG9yfVxuYDsKICAgICAgICB0ZXN0VGV4dCArPSBgICAgICDCoVR1IGltcHJlc29yYSBlc3RhIGxpc3RhIHBhcmEgb3BlcmFyISBcbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYCR7c2VwYXJhdG9yfVxuYDsKCiAgICAgICAgY29uc3QgY2h1bmtzID0gWwogICAgICAgICAgQnVmZmVyLmZyb20oRVNDX0lOSVQsICdiaW5hcnknKSwKICAgICAgICAgIEJ1ZmZlci5mcm9tKHRlc3RUZXh0LCAnbGF0aW4xJyksCiAgICAgICAgICBCdWZmZXIuZnJvbSgnXG5cblxuXG4nLCAnbGF0aW4xJyksCiAgICAgICAgICBCdWZmZXIuZnJvbShFU0NfQ1VUX1BBUlRJQUwsICdiaW5hcnknKQogICAgICAgIF07CgogICAgICAgIGNvbnN0IGZpbmFsQnVmZmVyID0gQnVmZmVyLmNvbmNhdChjaHVua3MpOwogICAgICAgIGF3YWl0IHByaW50V2luZG93c1Nwb29sZXIocHJpbnRlck5hbWUsIGZpbmFsQnVmZmVyKTsKCiAgICAgICAgcmV0dXJuIHJlcy5lbmQoSlNPTi5zdHJpbmdpZnkoewogICAgICAgICAgc3VjY2VzczogdHJ1ZSwKICAgICAgICAgIG1lc3NhZ2U6IGBUaWNrZXQgZGUgcHJ1ZWJhIGltcHJlc28gZXhpdG9zYW1lbnRlIGVuICR7cHJpbnRlck5hbWUgfHwgJ0ltcHJlc29yYSBQcmVkZXRlcm1pbmFkYSd9YAogICAgICAgIH0pKTsKICAgICAgfSBjYXRjaCAoZXJyKSB7CiAgICAgICAgY29uc29sZS5lcnJvcignW1ByaW50QnJpZGdlXSBFcnJvciBhbCBpbXByaW1pciB0ZXN0OicsIGVycik7CiAgICAgICAgcmV0dXJuIHJlcy53cml0ZUhlYWQoNTAwKS5lbmQoSlNPTi5zdHJpbmdpZnkoeyBzdWNjZXNzOiBmYWxzZSwgZXJyb3I6IGVyci5tZXNzYWdlIH0pKTsKICAgICAgfQogICAgfSk7CiAgICByZXR1cm47CiAgfQoKICAvLyA0MDQKICByZXMud3JpdGVIZWFkKDQwNCkuZW5kKEpTT04uc3RyaW5naWZ5KHsgZXJyb3I6ICdFbmRwb2ludCBubyBlbmNvbnRyYWRvJyB9KSk7Cn0pOwoKc2VydmVyLmxpc3RlbihQT1JULCBIT1NULCAoKSA9PiB7CiAgY29uc29sZS5sb2coJz09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0nKTsKICBjb25zb2xlLmxvZyhg4pyFIEtBTUlBIE5vZGUuanMgUHJpbnQgQnJpZGdlIHYyLjAgaW5pY2lhZG9gKTsKICBjb25zb2xlLmxvZyhgICAgRXNjdWNoYW5kbyBlbjogaHR0cDovL2xvY2FsaG9zdDoke1BPUlR9YCk7CiAgY29uc29sZS5sb2coYCAgIE5vZGUuanM6ICR7cHJvY2Vzcy52ZXJzaW9ufSDigJQgUGxhdGFmb3JtYTogJHtvcy5wbGF0Zm9ybSgpfWApOwogIGNvbnNvbGUubG9nKCc9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09Jyk7Cn0pOwo='))"\r
)\r
echo [OK] Iniciando KAMIA Print Bridge en http://localhost:8088...\r
echo.\r
cd /d "%TARGET_DIR%"\r
node bridge.js\r
pause\r
`;
    const blob = new Blob([batContent], { type: 'application/bat' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'iniciar-bridge.bat';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    addToast('Script iniciar-bridge.bat descargado (Auto-extraíble)', 'success');
  };

  const downloadInstallerBat = () => {
    const batContent = `@echo off\r
title KAMIA POS - Instalador de Servicio Print Bridge\r
color 0B\r
cls\r
echo ======================================================================\r
echo           KAMIA POS - INSTALADOR DE SERVICIO PRINT BRIDGE (NODE.JS)\r
echo ======================================================================\r
echo.\r
where node >nul 2>nul\r
if %errorlevel% neq 0 (\r
    color 0C\r
    echo [ERROR] Node.js no esta instalado.\r
    echo Descargando Node.js LTS oficial...\r
    start https://nodejs.org/dist/v20.18.0/node-v20.18.0-x64.msi\r
    pause\r
    exit /b 1\r
)\r
for /f "tokens=*" %%i in ('node -v') do set NODE_VERSION=%%i\r
echo   [1/4] Node.js verificado: %NODE_VERSION%\r
set "TARGET_DIR=%LOCALAPPDATA%\\GastrosPOS\\PrintBridge"\r
if not exist "%TARGET_DIR%" mkdir "%TARGET_DIR%"\r
set "BRIDGE_FILE=%TARGET_DIR%\\bridge.js"\r
if exist "%~dp0bridge.js" (\r
    copy /y "%~dp0bridge.js" "%BRIDGE_FILE%" >nul\r
) else (\r
    powershell -NoProfile -ExecutionPolicy Bypass -Command "[System.IO.File]::WriteAllBytes('$env:LOCALAPPDATA\\GastrosPOS\\PrintBridge\\bridge.js', [System.Convert]::FromBase64String('LyoqCiAqIEtBTUlBIGJ5IEpGIOKAlCBOb2RlLmpzIFRoZXJtYWwgUHJpbnQgQnJpZGdlIHYyLjAKICogU2Vydmlkb3IgSFRUUCBsb2NhbCBwYXJhIGltcHJlc2nDs24gdMOpcm1pY2Egc2lsZW5jaW9zYSBkaXJlY3RhIChFU0MvUE9TKQogKiBQdWVydG8gcG9yIGRlZmVjdG86IDgwODgKICovCgpjb25zdCBodHRwID0gcmVxdWlyZSgnaHR0cCcpOwpjb25zdCBmcyA9IHJlcXVpcmUoJ2ZzJyk7CmNvbnN0IHBhdGggPSByZXF1aXJlKCdwYXRoJyk7CmNvbnN0IG9zID0gcmVxdWlyZSgnb3MnKTsKY29uc3QgeyBleGVjLCBleGVjRmlsZSB9ID0gcmVxdWlyZSgnY2hpbGRfcHJvY2VzcycpOwpjb25zdCBuZXQgPSByZXF1aXJlKCduZXQnKTsKCmNvbnN0IFBPUlQgPSBwcm9jZXNzLmVudi5QT1JUIHx8IDgwODg7CmNvbnN0IEhPU1QgPSAnMC4wLjAuMCc7CgovLyBDb21hbmRvcyBFU0MvUE9TIGVzdMOhbmRhcgpjb25zdCBFU0MgPSAnXHgxQic7CmNvbnN0IEdTID0gJ1x4MUQnOwpjb25zdCBFU0NfSU5JVCA9IGAke0VTQ31AYDsgICAgICAgICAgICAgICAvLyBJbmljaWFsaXphciBpbXByZXNvcmEKY29uc3QgRVNDX0NVVF9GVUxMID0gYCR7R1N9Vlx4MDBgOyAgICAgICAgLy8gQ29ydGUgdG90YWwKY29uc3QgRVNDX0NVVF9QQVJUSUFMID0gYCR7R1N9Vlx4MDFgOyAgICAgLy8gQ29ydGUgcGFyY2lhbApjb25zdCBFU0NfRFJBV0VSID0gYCR7RVNDfXBceDAwXHgxOVx4RkFgOyAvLyBBYnJpciBnYXZldGEgLyBjYWrDs24gbW9uZWRlcm8KY29uc3QgRVNDX0FMSUdOX0xFRlQgPSBgJHtFU0N9YVx4MDBgOwpjb25zdCBFU0NfQUxJR05fQ0VOVEVSID0gYCR7RVNDfWFceDAxYDsKY29uc3QgRVNDX0FMSUdOX1JJR0hUID0gYCR7RVNDfWFceDAyYDsKY29uc3QgRVNDX0JPTERfT04gPSBgJHtFU0N9RVx4MDFgOwpjb25zdCBFU0NfQk9MRF9PRkYgPSBgJHtFU0N9RVx4MDBgOwoKLyoqCiAqIE9idGVuZXIgbGlzdGEgZGUgaW1wcmVzb3JhcyBkZSBXaW5kb3dzIHVzYW5kbyBQb3dlclNoZWxsCiAqLwpmdW5jdGlvbiBnZXRXaW5kb3dzUHJpbnRlcnMoKSB7CiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiB7CiAgICBjb25zdCBwc0NtZCA9IGBHZXQtQ2ltSW5zdGFuY2UgV2luMzJfUHJpbnRlciB8IFNlbGVjdC1PYmplY3QgTmFtZSwgRGVmYXVsdCwgUG9ydE5hbWUsIERyaXZlck5hbWUsIFByaW50ZXJTdGF0dXMgfCBDb252ZXJ0VG8tSnNvbiAtQ29tcHJlc3NgOwogICAgZXhlY0ZpbGUoJ3Bvd2Vyc2hlbGwnLCBbJy1Ob1Byb2ZpbGUnLCAnLUV4ZWN1dGlvblBvbGljeScsICdCeXBhc3MnLCAnLUNvbW1hbmQnLCBwc0NtZF0sIHsgd2luZG93c0hpZGU6IHRydWUsIHRpbWVvdXQ6IDYwMDAgfSwgKGVyciwgc3Rkb3V0KSA9PiB7CiAgICAgIGlmIChlcnIgfHwgIXN0ZG91dC50cmltKCkpIHsKICAgICAgICAvLyBGYWxsYmFjayByw6FwaWRvIHVzYW5kbyB3bWljCiAgICAgICAgZXhlYygnd21pYyBwcmludGVyIGdldCBuYW1lLGRlZmF1bHQgL2Zvcm1hdDpjc3YnLCB7IHdpbmRvd3NIaWRlOiB0cnVlLCB0aW1lb3V0OiA0MDAwIH0sICh3bWljRXJyLCB3bWljT3V0KSA9PiB7CiAgICAgICAgICBpZiAod21pY0VyciB8fCAhd21pY091dCkgewogICAgICAgICAgICByZXR1cm4gcmVzb2x2ZShbeyBuYW1lOiAnSW1wcmVzb3JhIFByZWRldGVybWluYWRhIGRlIFdpbmRvd3MnLCBpc0RlZmF1bHQ6IHRydWUsIHBvcnQ6ICdERUZBVUxUJyB9XSk7CiAgICAgICAgICB9CiAgICAgICAgICBjb25zdCBsaW5lcyA9IHdtaWNPdXQuc3BsaXQoJ1xuJykubWFwKGwgPT4gbC50cmltKCkpLmZpbHRlcihCb29sZWFuKS5zbGljZSgxKTsKICAgICAgICAgIGNvbnN0IHByaW50ZXJzID0gbGluZXMubWFwKGxpbmUgPT4gewogICAgICAgICAgICBjb25zdCBwYXJ0cyA9IGxpbmUuc3BsaXQoJywnKTsKICAgICAgICAgICAgaWYgKHBhcnRzLmxlbmd0aCA+PSAzKSB7CiAgICAgICAgICAgICAgcmV0dXJuIHsgbmFtZTogcGFydHNbMl0udHJpbSgpLCBpc0RlZmF1bHQ6IHBhcnRzWzFdLnRyaW0oKS50b0xvd2VyQ2FzZSgpID09PSAndHJ1ZScsIHBvcnQ6ICdVU0IvTFBUJyB9OwogICAgICAgICAgICB9CiAgICAgICAgICAgIHJldHVybiBudWxsOwogICAgICAgICAgfSkuZmlsdGVyKEJvb2xlYW4pOwogICAgICAgICAgcmVzb2x2ZShwcmludGVycy5sZW5ndGggPiAwID8gcHJpbnRlcnMgOiBbeyBuYW1lOiAnSW1wcmVzb3JhIFByZWRldGVybWluYWRhIGRlIFdpbmRvd3MnLCBpc0RlZmF1bHQ6IHRydWUsIHBvcnQ6ICdERUZBVUxUJyB9XSk7CiAgICAgICAgfSk7CiAgICAgICAgcmV0dXJuOwogICAgICB9CgogICAgICB0cnkgewogICAgICAgIGxldCBkYXRhID0gSlNPTi5wYXJzZShzdGRvdXQpOwogICAgICAgIGlmICghQXJyYXkuaXNBcnJheShkYXRhKSkgZGF0YSA9IFtkYXRhXTsKICAgICAgICBjb25zdCBwcmludGVycyA9IGRhdGEubWFwKHAgPT4gKHsKICAgICAgICAgIG5hbWU6IHAuTmFtZSB8fCAnSW1wcmVzb3JhJywKICAgICAgICAgIGlzRGVmYXVsdDogQm9vbGVhbihwLkRlZmF1bHQpLAogICAgICAgICAgcG9ydDogcC5Qb3J0TmFtZSB8fCAnJywKICAgICAgICAgIGRyaXZlcjogcC5Ecml2ZXJOYW1lIHx8ICcnLAogICAgICAgICAgc3RhdHVzOiBwLlByaW50ZXJTdGF0dXMgfHwgMwogICAgICAgIH0pKTsKICAgICAgICByZXNvbHZlKHByaW50ZXJzKTsKICAgICAgfSBjYXRjaCAocGFyc2VFcnIpIHsKICAgICAgICByZXNvbHZlKFt7IG5hbWU6ICdJbXByZXNvcmEgUHJlZGV0ZXJtaW5hZGEgZGUgV2luZG93cycsIGlzRGVmYXVsdDogdHJ1ZSwgcG9ydDogJ0RFRkFVTFQnIH1dKTsKICAgICAgfQogICAgfSk7CiAgfSk7Cn0KCi8qKgogKiBJbXByaW1pciBSQVcgZW4gaW1wcmVzb3JhIGRlIHJlZCAoVENQIFNvY2tldCBwdWVydG8gOTEwMCkKICovCmZ1bmN0aW9uIHByaW50TmV0d29ya1NvY2tldChpcCwgcG9ydCA9IDkxMDAsIGJ1ZmZlcikgewogIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7CiAgICBjb25zdCBjbGllbnQgPSBuZXcgbmV0LlNvY2tldCgpOwogICAgY2xpZW50LnNldFRpbWVvdXQoNTAwMCk7CiAgICBjbGllbnQuY29ubmVjdChwb3J0LCBpcCwgKCkgPT4gewogICAgICBjbGllbnQud3JpdGUoYnVmZmVyLCAoKSA9PiB7CiAgICAgICAgY2xpZW50LmVuZCgpOwogICAgICAgIHJlc29sdmUodHJ1ZSk7CiAgICAgIH0pOwogICAgfSk7CiAgICBjbGllbnQub24oJ2Vycm9yJywgKGVycikgPT4gcmVqZWN0KGVycikpOwogICAgY2xpZW50Lm9uKCd0aW1lb3V0JywgKCkgPT4gewogICAgICBjbGllbnQuZGVzdHJveSgpOwogICAgICByZWplY3QobmV3IEVycm9yKGBUaW1lb3V0IGRlIGNvbmV4acOzbiBhIGxhIGltcHJlc29yYSBlbiAke2lwfToke3BvcnR9YCkpOwogICAgfSk7CiAgfSk7Cn0KCi8qKgogKiBJbXByaW1pciBlbiBpbXByZXNvcmEgbG9jYWwvY29tcGFydGlkYSBkZSBXaW5kb3dzCiAqLwpmdW5jdGlvbiBwcmludFdpbmRvd3NTcG9vbGVyKHByaW50ZXJOYW1lLCBidWZmZXIpIHsKICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4gewogICAgY29uc3QgdGVtcEZpbGUgPSBwYXRoLmpvaW4ob3MudG1wZGlyKCksIGBrYW1pYV9wcmludF8ke0RhdGUubm93KCl9XyR7TWF0aC5yYW5kb20oKS50b1N0cmluZygzNikuc3Vic3RyKDIsIDYpfS5iaW5gKTsKICAgIAogICAgZnMud3JpdGVGaWxlKHRlbXBGaWxlLCBidWZmZXIsICh3cml0ZUVycikgPT4gewogICAgICBpZiAod3JpdGVFcnIpIHJldHVybiByZWplY3Qod3JpdGVFcnIpOwoKICAgICAgLy8gVXNhciBzY3JpcHQgUG93ZXJTaGVsbCBlbWJlYmlkbyBwYXJhIGVudmlhciBsb3MgYnl0ZXMgUkFXIGFsIHNwb29sZXIgZGUgbGEgaW1wcmVzb3JhCiAgICAgIGNvbnN0IHRhcmdldFByaW50ZXIgPSBwcmludGVyTmFtZSAmJiBwcmludGVyTmFtZSAhPT0gJ0ltcHJlc29yYSBQcmVkZXRlcm1pbmFkYSBkZSBXaW5kb3dzJwogICAgICAgID8gcHJpbnRlck5hbWUucmVwbGFjZSgvJy9nLCAiJyciKQogICAgICAgIDogJyc7CgogICAgICBjb25zdCBwc1NjcmlwdCA9IGAKJHRlbXBGaWxlID0gJyR7dGVtcEZpbGUucmVwbGFjZSgvJy9nLCAiJyciKX0nOwokcHJpbnRlck5hbWUgPSAnJHt0YXJnZXRQcmludGVyfSc7CgppZiAoLW5vdCAkcHJpbnRlck5hbWUpIHsKICAkZGVmYXVsdFByaW50ZXIgPSBHZXQtQ2ltSW5zdGFuY2UgV2luMzJfUHJpbnRlciB8IFdoZXJlLU9iamVjdCB7ICRfLkRlZmF1bHQgLWVxICR0cnVlIH0gfCBTZWxlY3QtT2JqZWN0IC1GaXJzdCAxOwogIGlmICgkZGVmYXVsdFByaW50ZXIpIHsgJHByaW50ZXJOYW1lID0gJGRlZmF1bHRQcmludGVyLk5hbWUgfQogIGVsc2UgewogICAgJGFueVByaW50ZXIgPSBHZXQtQ2ltSW5zdGFuY2UgV2luMzJfUHJpbnRlciB8IFNlbGVjdC1PYmplY3QgLUZpcnN0IDE7CiAgICBpZiAoJGFueVByaW50ZXIpIHsgJHByaW50ZXJOYW1lID0gJGFueVByaW50ZXIuTmFtZSB9CiAgfQp9CgppZiAoLW5vdCAkcHJpbnRlck5hbWUpIHsKICBleGl0IDEKfQoKIyBFbnZpYXIgYWwgc3Bvb2xlcgp0cnkgewogIEdldC1Db250ZW50IC1QYXRoICR0ZW1wRmlsZSAtRW5jb2RpbmcgRGVmYXVsdCB8IE91dC1QcmludGVyIC1OYW1lICRwcmludGVyTmFtZSAtRXJyb3JBY3Rpb24gU3RvcAogIGV4aXQgMAp9IGNhdGNoIHsKICB0cnkgewogICAgW1N5c3RlbS5JTy5GaWxlXTo6UmVhZEFsbFRleHQoJHRlbXBGaWxlKSB8IE91dC1QcmludGVyIC1OYW1lICRwcmludGVyTmFtZSAtRXJyb3JBY3Rpb24gU3RvcAogICAgZXhpdCAwCiAgfSBjYXRjaCB7CiAgICBXcml0ZS1FcnJvciAkXy5FeGNlcHRpb24uTWVzc2FnZQogICAgZXhpdCAxCiAgfQp9CiAgICAgIGAudHJpbSgpOwoKICAgICAgZXhlY0ZpbGUoJ3Bvd2Vyc2hlbGwnLCBbJy1Ob1Byb2ZpbGUnLCAnLUV4ZWN1dGlvblBvbGljeScsICdCeXBhc3MnLCAnLUNvbW1hbmQnLCBwc1NjcmlwdF0sIHsgd2luZG93c0hpZGU6IHRydWUsIHRpbWVvdXQ6IDgwMDAgfSwgKHBzRXJyKSA9PiB7CiAgICAgICAgLy8gTGltcGlhciBhcmNoaXZvIHRlbXBvcmFsCiAgICAgICAgdHJ5IHsgZnMudW5saW5rU3luYyh0ZW1wRmlsZSk7IH0gY2F0Y2ggKGUpIHt9CgogICAgICAgIGlmIChwc0VycikgewogICAgICAgICAgY29uc29sZS5lcnJvcihgW1ByaW50QnJpZGdlXSBFcnJvciBhbCBlbnZpYXIgYSBzcG9vbGVyICgke3ByaW50ZXJOYW1lIHx8ICdEZWZhdWx0J30pOmAsIHBzRXJyLm1lc3NhZ2UpOwogICAgICAgICAgcmV0dXJuIHJlamVjdChuZXcgRXJyb3IoYEVycm9yIGFsIGVudmlhciB0cmFiYWpvIGEgbGEgaW1wcmVzb3JhICR7cHJpbnRlck5hbWUgfHwgJ0RlZmF1bHQnfTogJHtwc0Vyci5tZXNzYWdlfWApKTsKICAgICAgICB9CiAgICAgICAgcmVzb2x2ZSh0cnVlKTsKICAgICAgfSk7CiAgICB9KTsKICB9KTsKfQoKLyoqCiAqIFNlcnZpZG9yIEhUVFAKICovCmNvbnN0IHNlcnZlciA9IGh0dHAuY3JlYXRlU2VydmVyKGFzeW5jIChyZXEsIHJlcykgPT4gewogIC8vIENPUlMgSGVhZGVycwogIHJlcy5zZXRIZWFkZXIoJ0FjY2Vzcy1Db250cm9sLUFsbG93LU9yaWdpbicsICcqJyk7CiAgcmVzLnNldEhlYWRlcignQWNjZXNzLUNvbnRyb2wtQWxsb3ctTWV0aG9kcycsICdHRVQsIFBPU1QsIE9QVElPTlMnKTsKICByZXMuc2V0SGVhZGVyKCdBY2Nlc3MtQ29udHJvbC1BbGxvdy1IZWFkZXJzJywgJ0NvbnRlbnQtVHlwZSwgQXV0aG9yaXphdGlvbicpOwogIHJlcy5zZXRIZWFkZXIoJ0NvbnRlbnQtVHlwZScsICdhcHBsaWNhdGlvbi9qc29uOyBjaGFyc2V0PXV0Zi04Jyk7CgogIGlmIChyZXEubWV0aG9kID09PSAnT1BUSU9OUycpIHsKICAgIHJlcy53cml0ZUhlYWQoMjAwKTsKICAgIHJldHVybiByZXMuZW5kKCk7CiAgfQoKICBjb25zdCB1cmwgPSByZXEudXJsLnNwbGl0KCc/JylbMF07CgogIC8vIDEuIEdFVCAvaGVhbHRoIG8gL3N0YXR1cwogIGlmIChyZXEubWV0aG9kID09PSAnR0VUJyAmJiAodXJsID09PSAnLycgfHwgdXJsID09PSAnL2hlYWx0aCcgfHwgdXJsID09PSAnL3N0YXR1cycpKSB7CiAgICByZXR1cm4gcmVzLmVuZChKU09OLnN0cmluZ2lmeSh7CiAgICAgIHN0YXR1czogJ29ubGluZScsCiAgICAgIHNlcnZpY2U6ICdLQU1JQSBOb2RlLmpzIFByaW50IEJyaWRnZScsCiAgICAgIHZlcnNpb246ICcyLjAuMCcsCiAgICAgIG5vZGVWZXJzaW9uOiBwcm9jZXNzLnZlcnNpb24sCiAgICAgIHBsYXRmb3JtOiBvcy5wbGF0Zm9ybSgpLAogICAgICBhcmNoOiBvcy5hcmNoKCksCiAgICAgIGhvc3RuYW1lOiBvcy5ob3N0bmFtZSgpLAogICAgICB1cHRpbWVTZWNvbmRzOiBNYXRoLmZsb29yKHByb2Nlc3MudXB0aW1lKCkpLAogICAgICB0aW1lc3RhbXA6IG5ldyBEYXRlKCkudG9JU09TdHJpbmcoKQogICAgfSkpOwogIH0KCiAgLy8gMi4gR0VUIC9wcmludGVycwogIGlmIChyZXEubWV0aG9kID09PSAnR0VUJyAmJiB1cmwgPT09ICcvcHJpbnRlcnMnKSB7CiAgICB0cnkgewogICAgICBjb25zdCBwcmludGVycyA9IGF3YWl0IGdldFdpbmRvd3NQcmludGVycygpOwogICAgICByZXR1cm4gcmVzLmVuZChKU09OLnN0cmluZ2lmeSh7IHN1Y2Nlc3M6IHRydWUsIHByaW50ZXJzIH0pKTsKICAgIH0gY2F0Y2ggKGVycikgewogICAgICByZXR1cm4gcmVzLndyaXRlSGVhZCg1MDApLmVuZChKU09OLnN0cmluZ2lmeSh7IHN1Y2Nlc3M6IGZhbHNlLCBlcnJvcjogZXJyLm1lc3NhZ2UgfSkpOwogICAgfQogIH0KCiAgLy8gMy4gUE9TVCAvcHJpbnQKICBpZiAocmVxLm1ldGhvZCA9PT0gJ1BPU1QnICYmIHVybCA9PT0gJy9wcmludCcpIHsKICAgIGxldCBib2R5ID0gJyc7CiAgICByZXEub24oJ2RhdGEnLCBjaHVuayA9PiB7IGJvZHkgKz0gY2h1bms7IH0pOwogICAgcmVxLm9uKCdlbmQnLCBhc3luYyAoKSA9PiB7CiAgICAgIHRyeSB7CiAgICAgICAgY29uc3QgcGF5bG9hZCA9IEpTT04ucGFyc2UoYm9keSB8fCAne30nKTsKICAgICAgICBjb25zdCB7IHRleHQsIHJhdywgcHJpbnRlck5hbWUsIGN1dFBhcGVyID0gdHJ1ZSwgb3BlbkRyYXdlciA9IGZhbHNlLCBpcCA9IG51bGwsIHBvcnQgPSA5MTAwIH0gPSBwYXlsb2FkOwoKICAgICAgICBpZiAoIXRleHQgJiYgIXJhdykgewogICAgICAgICAgcmV0dXJuIHJlcy53cml0ZUhlYWQoNDAwKS5lbmQoSlNPTi5zdHJpbmdpZnkoeyBzdWNjZXNzOiBmYWxzZSwgZXJyb3I6ICdFbCBjYW1wbyAidGV4dCIgbyAicmF3IiBlcyByZXF1ZXJpZG8nIH0pKTsKICAgICAgICB9CgogICAgICAgIC8vIENvbnN0cnVpciBidWZmZXIgRVNDL1BPUwogICAgICAgIGxldCBjaHVua3MgPSBbXTsKICAgICAgICBjaHVua3MucHVzaChCdWZmZXIuZnJvbShFU0NfSU5JVCwgJ2JpbmFyeScpKTsKCiAgICAgICAgaWYgKG9wZW5EcmF3ZXIpIHsKICAgICAgICAgIGNodW5rcy5wdXNoKEJ1ZmZlci5mcm9tKEVTQ19EUkFXRVIsICdiaW5hcnknKSk7CiAgICAgICAgfQoKICAgICAgICBpZiAodGV4dCkgewogICAgICAgICAgLy8gQ29kaWZpY2FyIGVuIExhdGluMS9DUDEyNTIgcGFyYSB0aWxkZXMgeSBjYXJhY3RlcmVzIGVuIGVzcGHDsW9sCiAgICAgICAgICBjaHVua3MucHVzaChCdWZmZXIuZnJvbSh0ZXh0LCAnbGF0aW4xJykpOwogICAgICAgIH0KCiAgICAgICAgaWYgKHJhdykgewogICAgICAgICAgY2h1bmtzLnB1c2goQnVmZmVyLmZyb20ocmF3LCAnYmluYXJ5JykpOwogICAgICAgIH0KCiAgICAgICAgLy8gU2FsdG9zIGRlIGzDrW5lYSB5IGNvcnRlIGRlIHBhcGVsIGF1dG9tw6F0aWNvCiAgICAgICAgaWYgKGN1dFBhcGVyICE9PSBmYWxzZSkgewogICAgICAgICAgY2h1bmtzLnB1c2goQnVmZmVyLmZyb20oJ1xuXG5cblxuJywgJ2xhdGluMScpKTsKICAgICAgICAgIGNodW5rcy5wdXNoKEJ1ZmZlci5mcm9tKEVTQ19DVVRfUEFSVElBTCwgJ2JpbmFyeScpKTsKICAgICAgICB9CgogICAgICAgIGNvbnN0IGZpbmFsQnVmZmVyID0gQnVmZmVyLmNvbmNhdChjaHVua3MpOwoKICAgICAgICAvLyBTaSBlcyBpbXByZXNvcmEgSVAgcG9yIHJlZAogICAgICAgIGlmIChpcCkgewogICAgICAgICAgYXdhaXQgcHJpbnROZXR3b3JrU29ja2V0KGlwLCBwb3J0LCBmaW5hbEJ1ZmZlcik7CiAgICAgICAgICByZXR1cm4gcmVzLmVuZChKU09OLnN0cmluZ2lmeSh7IHN1Y2Nlc3M6IHRydWUsIG1lc3NhZ2U6IGBJbXByZXNpw7NuIGVudmlhZGEgYSBzb2NrZXQgZGUgcmVkICR7aXB9OiR7cG9ydH1gIH0pKTsKICAgICAgICB9CgogICAgICAgIC8vIFNpIGVzIGltcHJlc29yYSBkZSBXaW5kb3dzIFNwb29sZXIKICAgICAgICBhd2FpdCBwcmludFdpbmRvd3NTcG9vbGVyKHByaW50ZXJOYW1lLCBmaW5hbEJ1ZmZlcik7CiAgICAgICAgcmV0dXJuIHJlcy5lbmQoSlNPTi5zdHJpbmdpZnkoeyBzdWNjZXNzOiB0cnVlLCBtZXNzYWdlOiBgVHJhYmFqbyBlbnZpYWRvIGEgbGEgY29sYSBkZSAke3ByaW50ZXJOYW1lIHx8ICdJbXByZXNvcmEgUHJlZGV0ZXJtaW5hZGEnfWAgfSkpOwoKICAgICAgfSBjYXRjaCAoZXJyKSB7CiAgICAgICAgY29uc29sZS5lcnJvcignW1ByaW50QnJpZGdlXSBFcnJvciBhbCBwcm9jZXNhciBpbXByZXNpw7NuOicsIGVycik7CiAgICAgICAgcmV0dXJuIHJlcy53cml0ZUhlYWQoNTAwKS5lbmQoSlNPTi5zdHJpbmdpZnkoeyBzdWNjZXNzOiBmYWxzZSwgZXJyb3I6IGVyci5tZXNzYWdlIH0pKTsKICAgICAgfQogICAgfSk7CiAgICByZXR1cm47CiAgfQoKICAvLyA0LiBQT1NUIC90ZXN0LXByaW50CiAgaWYgKHJlcS5tZXRob2QgPT09ICdQT1NUJyAmJiB1cmwgPT09ICcvdGVzdC1wcmludCcpIHsKICAgIGxldCBib2R5ID0gJyc7CiAgICByZXEub24oJ2RhdGEnLCBjaHVuayA9PiB7IGJvZHkgKz0gY2h1bms7IH0pOwogICAgcmVxLm9uKCdlbmQnLCBhc3luYyAoKSA9PiB7CiAgICAgIHRyeSB7CiAgICAgICAgY29uc3QgcGF5bG9hZCA9IEpTT04ucGFyc2UoYm9keSB8fCAne30nKTsKICAgICAgICBjb25zdCBwcmludGVyTmFtZSA9IHBheWxvYWQucHJpbnRlck5hbWUgfHwgbnVsbDsKICAgICAgICBjb25zdCB0ZXN0VHlwZSA9IHBheWxvYWQudHlwZSB8fCAnY29tYW5kYSc7CgogICAgICAgIGNvbnN0IG5vdyA9IG5ldyBEYXRlKCkudG9Mb2NhbGVTdHJpbmcoJ2VzLUNPJyk7CiAgICAgICAgY29uc3Qgc2VwYXJhdG9yID0gJz09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0nOwogICAgICAgIGNvbnN0IGxpbmUgPSAnLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLSc7CgogICAgICAgIGxldCB0ZXN0VGV4dCA9ICcnOwogICAgICAgIHRlc3RUZXh0ICs9IGAke3NlcGFyYXRvcn1cbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYCAgICAgICAgICBLQU1JQSBQT1MgJiBFUlAgYnkgSkYgICAgICAgICBcbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYCAgICAgICJUb2RvIHR1IG5lZ29jaW8sIGNvbmVjdGFkby4iICAgICBcbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYCR7c2VwYXJhdG9yfVxuYDsKICAgICAgICB0ZXN0VGV4dCArPSBgICAgKioqIFRJQ0tFVCBERSBQUlVFQkEgREUgSU1QUkVTSU9OICoqKiBcbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYCR7bGluZX1cbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYEZlY2hhIC8gSG9yYTogICR7bm93fVxuYDsKICAgICAgICB0ZXN0VGV4dCArPSBgU2VydmljaW86ICAgICAgS0FNSUEgTm9kZS5qcyBQcmludCBCcmlkZ2UgdjIuMFxuYDsKICAgICAgICB0ZXN0VGV4dCArPSBgTW90b3I6ICAgICAgICAgTm9kZS5qcyAke3Byb2Nlc3MudmVyc2lvbn1cbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYEltcHJlc29yYTogICAgICR7cHJpbnRlck5hbWUgfHwgJ1ByZWRldGVybWluYWRhIGRlIFdpbmRvd3MnfVxuYDsKICAgICAgICB0ZXN0VGV4dCArPSBgRGVzdGlubzogICAgICAgJHt0ZXN0VHlwZSA9PT0gJ2NvY2luYScgPyAnQ29jaW5hIChDb21hbmRhKScgOiAodGVzdFR5cGUgPT09ICdjYWphJyA/ICdDYWphIChGYWN0dXJhY2nDs24pJyA6ICdHZW5lcmFsJyl9XG5gOwogICAgICAgIHRlc3RUZXh0ICs9IGAke2xpbmV9XG5gOwogICAgICAgIHRlc3RUZXh0ICs9IGBDYXJhY3RlcmVzIEVzcGVjaWFsZXMgLyBBY2VudG9zOlxuYDsKICAgICAgICB0ZXN0VGV4dCArPSBgw6Egw6kgw60gw7Mgw7ogw7Egw4Egw4kgw40gw5Mgw5ogw5EgJCAlICYgQCAjXG5gOwogICAgICAgIHRlc3RUZXh0ICs9IGAke2xpbmV9XG5gOwogICAgICAgIHRlc3RUZXh0ICs9IGBFc3RhZG86ICAgICAgICBDT05FWElPTiAxMDAlIEVYSVRPU0FcbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYEltcHJlc2lvbjogICAgIERpcmVjdGEgeSBTaWxlbmNpb3NhIChPSylcbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYCR7c2VwYXJhdG9yfVxuYDsKICAgICAgICB0ZXN0VGV4dCArPSBgICAgICDCoVR1IGltcHJlc29yYSBlc3RhIGxpc3RhIHBhcmEgb3BlcmFyISBcbmA7CiAgICAgICAgdGVzdFRleHQgKz0gYCR7c2VwYXJhdG9yfVxuYDsKCiAgICAgICAgY29uc3QgY2h1bmtzID0gWwogICAgICAgICAgQnVmZmVyLmZyb20oRVNDX0lOSVQsICdiaW5hcnknKSwKICAgICAgICAgIEJ1ZmZlci5mcm9tKHRlc3RUZXh0LCAnbGF0aW4xJyksCiAgICAgICAgICBCdWZmZXIuZnJvbSgnXG5cblxuXG4nLCAnbGF0aW4xJyksCiAgICAgICAgICBCdWZmZXIuZnJvbShFU0NfQ1VUX1BBUlRJQUwsICdiaW5hcnknKQogICAgICAgIF07CgogICAgICAgIGNvbnN0IGZpbmFsQnVmZmVyID0gQnVmZmVyLmNvbmNhdChjaHVua3MpOwogICAgICAgIGF3YWl0IHByaW50V2luZG93c1Nwb29sZXIocHJpbnRlck5hbWUsIGZpbmFsQnVmZmVyKTsKCiAgICAgICAgcmV0dXJuIHJlcy5lbmQoSlNPTi5zdHJpbmdpZnkoewogICAgICAgICAgc3VjY2VzczogdHJ1ZSwKICAgICAgICAgIG1lc3NhZ2U6IGBUaWNrZXQgZGUgcHJ1ZWJhIGltcHJlc28gZXhpdG9zYW1lbnRlIGVuICR7cHJpbnRlck5hbWUgfHwgJ0ltcHJlc29yYSBQcmVkZXRlcm1pbmFkYSd9YAogICAgICAgIH0pKTsKICAgICAgfSBjYXRjaCAoZXJyKSB7CiAgICAgICAgY29uc29sZS5lcnJvcignW1ByaW50QnJpZGdlXSBFcnJvciBhbCBpbXByaW1pciB0ZXN0OicsIGVycik7CiAgICAgICAgcmV0dXJuIHJlcy53cml0ZUhlYWQoNTAwKS5lbmQoSlNPTi5zdHJpbmdpZnkoeyBzdWNjZXNzOiBmYWxzZSwgZXJyb3I6IGVyci5tZXNzYWdlIH0pKTsKICAgICAgfQogICAgfSk7CiAgICByZXR1cm47CiAgfQoKICAvLyA0MDQKICByZXMud3JpdGVIZWFkKDQwNCkuZW5kKEpTT04uc3RyaW5naWZ5KHsgZXJyb3I6ICdFbmRwb2ludCBubyBlbmNvbnRyYWRvJyB9KSk7Cn0pOwoKc2VydmVyLmxpc3RlbihQT1JULCBIT1NULCAoKSA9PiB7CiAgY29uc29sZS5sb2coJz09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0nKTsKICBjb25zb2xlLmxvZyhg4pyFIEtBTUlBIE5vZGUuanMgUHJpbnQgQnJpZGdlIHYyLjAgaW5pY2lhZG9gKTsKICBjb25zb2xlLmxvZyhgICAgRXNjdWNoYW5kbyBlbjogaHR0cDovL2xvY2FsaG9zdDoke1BPUlR9YCk7CiAgY29uc29sZS5sb2coYCAgIE5vZGUuanM6ICR7cHJvY2Vzcy52ZXJzaW9ufSDigJQgUGxhdGFmb3JtYTogJHtvcy5wbGF0Zm9ybSgpfWApOwogIGNvbnNvbGUubG9nKCc9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09Jyk7Cn0pOwo='))"\r
)\r
echo   [2/4] Archivos instalados en: %TARGET_DIR%\r
powershell -NoProfile -ExecutionPolicy Bypass -Command "try { Get-NetTCPConnection -LocalPort 8088 -ErrorAction SilentlyContinue | ForEach-Object { Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue } } catch {}"\r
set "STARTUP_FOLDER=%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup"\r
set "VBS_PATH=%STARTUP_FOLDER%\\KAMIA_PrintBridge.vbs"\r
echo Set WshShell = CreateObject("WScript.Shell") > "%VBS_PATH%"\r
echo WshShell.Run "node """ ^& "%TARGET_DIR%\\bridge.js"""", 0, False >> "%VBS_PATH%"\r
echo   [3/4] Inicio automatico con Windows configurado.\r
echo   [4/4] Iniciando servicio en segundo plano...\r
wscript "%VBS_PATH%"\r
echo.\r
echo ======================================================================\r
echo    INSTALACION COMPLETADA CON EXITO\r
echo ======================================================================\r
echo   [OK] Print Bridge activo en http://localhost:8088\r
echo   [OK] Se iniciara siempre al encender Windows.\r
echo.\r
pause >nul\r
`;
    const blob = new Blob([batContent], { type: 'application/bat' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'instalar-servicio.bat';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    addToast('Instalador instalar-servicio.bat descargado (Auto-extraíble)', 'success');
  };

  const downloadUninstallerBat = () => {
    const batContent = `@echo off\r
title KAMIA POS - Desinstalador de Print Bridge\r
color 0C\r
cls\r
echo ======================================================================\r
echo           KAMIA POS - DESINSTALADOR DE PRINT BRIDGE\r
echo ======================================================================\r
echo.\r
powershell -NoProfile -ExecutionPolicy Bypass -Command "try { Get-NetTCPConnection -LocalPort 8088 -ErrorAction SilentlyContinue | ForEach-Object { Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue } } catch {}; try { Get-CimInstance Win32_Process | Where-Object { $_.CommandLine -like '*PrintBridge*' } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue } } catch {}"\r
set "STARTUP_FOLDER=%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup"\r
set "VBS_PATH=%STARTUP_FOLDER%\\KAMIA_PrintBridge.vbs"\r
if exist "%VBS_PATH%" del /f /q "%VBS_PATH%"\r
set "TARGET_DIR=%LOCALAPPDATA%\\GastrosPOS\\PrintBridge"\r
if exist "%TARGET_DIR%" rmdir /s /q "%TARGET_DIR%"\r
echo   [OK] Print Bridge desinstalado exitosamente.\r
pause >nul\r
`;
    const blob = new Blob([batContent], { type: 'application/bat' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'desinstalar-servicio.bat';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    addToast('Desinstalador desinstalar-servicio.bat descargado', 'info');
  };

  // Opciones de impresoras detectadas
  const printerOptions = [
    { value: '', label: 'Impresora Predeterminada de Windows' },
    ...detectedPrinters.map(p => ({
      value: p.name,
      label: `${p.name} ${p.isDefault ? '(Predeterminada)' : ''}`
    }))
  ];

  if (loading) {
    return (
      <div style={{ padding: 'var(--space-6)', textAlign: 'center', color: 'var(--text-muted)' }}>
        Cargando configuración de impresión...
      </div>
    );
  }

  return (
    <div style={{ padding: 'var(--space-4)', maxWidth: '1200px', margin: '0 auto' }}>
      
      {/* Encabezado Principal */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px', flexWrap: 'wrap', gap: '12px' }}>
        <div>
          <h1 style={{ fontSize: '22px', fontWeight: 900, display: 'flex', alignItems: 'center', gap: '10px', margin: 0 }}>
            <Printer size={24} color="var(--accent-primary)" />
            Configuración de Impresión Térmica & Print Bridge
          </h1>
          <p style={{ margin: '4px 0 0 0', fontSize: '13px', color: 'var(--text-muted)' }}>
            Control centralizado de impresión directa silenciosa (ESC/POS), auto-impresión de comandas y gestión de impresoras.
          </p>
        </div>

        <div style={{ display: 'flex', gap: '8px' }}>
          <Button
            type="button"
            variant="secondary"
            icon={<RefreshCw size={14} />}
            onClick={testBridgeConnection}
          >
            Re-Escanear Bridge
          </Button>
          <Button
            type="button"
            variant="primary"
            icon={<Check size={16} />}
            onClick={handleSave}
            disabled={saving}
          >
            {saving ? 'Guardando...' : 'Guardar Cambios'}
          </Button>
        </div>
      </div>

      {/* MONITOR EN VIVO: ESTADO DE NODE.JS Y PRINT BRIDGE */}
      <Card style={{ padding: '16px 20px', marginBottom: '20px', background: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px' }}>
          
          <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
            <div style={{
              width: '48px',
              height: '48px',
              borderRadius: '12px',
              background: bridgeStatus === 'online' ? 'rgba(4, 120, 87, 0.15)' : 'rgba(220, 38, 38, 0.15)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: bridgeStatus === 'online' ? 'var(--accent-success)' : 'var(--accent-danger)'
            }}>
              <Cpu size={26} />
            </div>

            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <h3 style={{ fontSize: '16px', fontWeight: 800, margin: 0 }}>
                  Estado del Microservicio Print Bridge (Node.js)
                </h3>
                <Badge variant={bridgeStatus === 'online' ? 'success' : (bridgeStatus === 'checking' ? 'warning' : 'danger')}>
                  {bridgeStatus === 'online' ? '🟢 En Línea' : (bridgeStatus === 'checking' ? '🟡 Verificando...' : '🔴 Desconectado')}
                </Badge>
              </div>

              <div style={{ fontSize: '12px', color: 'var(--text-secondary)', marginTop: '4px' }}>
                {bridgeStatus === 'online' ? (
                  <span>
                    Servicio activo en <strong>{bridgeUrl}</strong> &bull; Motor <strong>Node.js {bridgeInfo?.nodeVersion || ''}</strong> &bull; {detectedPrinters.length} impresoras detectadas
                  </span>
                ) : (
                  <span>
                    El servicio local no está activo en el puerto 8088. Sigue los pasos inferiores para iniciarlo.
                  </span>
                )}
              </div>
            </div>
          </div>

          <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
            <Button
              size="sm"
              variant="secondary"
              icon={<Download size={14} />}
              onClick={downloadNodeInstaller}
              title="Descargar Node.js LTS Oficial de 64 bits"
            >
              📥 Instalar Node.js LTS
            </Button>
            <Button
              size="sm"
              variant="primary"
              icon={<Play size={14} />}
              onClick={downloadStarterBat}
            >
              🚀 Iniciar Bridge (.bat)
            </Button>
            <Button
              size="sm"
              variant="secondary"
              icon={<ShieldCheck size={14} />}
              onClick={downloadInstallerBat}
            >
              ⚡ Instalar Auto-Inicio (.bat)
            </Button>
          </div>

        </div>

        {/* Alerta interactiva si está desconectado */}
        {bridgeStatus === 'offline' && (
          <div style={{
            marginTop: '16px',
            padding: '14px 16px',
            borderRadius: '8px',
            background: 'rgba(239, 68, 68, 0.08)',
            border: '1px solid rgba(239, 68, 68, 0.3)',
            display: 'flex',
            gap: '12px',
            alignItems: 'flex-start'
          }}>
            <AlertCircle size={20} color="var(--accent-danger)" style={{ flexShrink: 0, marginTop: '2px' }} />
            <div>
              <strong style={{ color: 'var(--accent-danger)', fontSize: '13.5px' }}>
                ¿Cómo activar la Impresión Silenciosa en 2 pasos simples?
              </strong>
              <ol style={{ margin: '6px 0 0 0', paddingLeft: '20px', fontSize: '12px', color: 'var(--text-secondary)', lineHeight: '1.6' }}>
                <li>
                  <strong>Paso 1 (Obligatorio):</strong> Si no tienes Node.js, haz clic en el botón <span style={{ color: 'var(--accent-primary)', fontWeight: 700 }}>"📥 Instalar Node.js LTS"</span> y sigue el asistente oficial.
                </li>
                <li>
                  <strong>Paso 2:</strong> Haz clic en <span style={{ color: 'var(--accent-primary)', fontWeight: 700 }}>"🚀 Iniciar Bridge (.bat)"</span> o <span style={{ color: 'var(--accent-primary)', fontWeight: 700 }}>"⚡ Instalar Auto-Inicio (.bat)"</span> para dejar el puente activo permanentemente en segundo plano.
                </li>
              </ol>
            </div>
          </div>
        )}
      </Card>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', gap: '20px', marginBottom: '20px' }}>
        
        {/* ASIGNACIÓN DE IMPRESORAS DE DESTINO */}
        <Card style={{ padding: '18px', background: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}>
          <h3 style={{ fontSize: '15px', fontWeight: 800, margin: '0 0 14px 0', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <UtensilsCrossed size={17} color="var(--accent-primary)" />
            Asignación de Impresoras Térmicas
          </h3>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
            {/* Impresora Cocina */}
            <div>
              <Select
                label="🍳 Impresora de Cocina / Comandas"
                value={printerKitchenName}
                onChange={(e) => setPrinterKitchenName(e.target.value)}
                options={printerOptions}
              />
              <div style={{ fontSize: '11px', color: 'var(--text-muted)', marginTop: '3px' }}>
                Destino para tickets de preparación y órdenes de cocina.
              </div>
            </div>

            {/* Impresora Caja */}
            <div>
              <Select
                label="🧾 Impresora de Caja / Facturación POS"
                value={printerReceiptName}
                onChange={(e) => setPrinterReceiptName(e.target.value)}
                options={printerOptions}
              />
              <div style={{ fontSize: '11px', color: 'var(--text-muted)', marginTop: '3px' }}>
                Destino para facturas de venta, pre-facturas y recibos de cobro.
              </div>
            </div>

            {/* Impresora Bar */}
            <div>
              <Select
                label="🍸 Impresora de Bar / Coctelería (Opcional)"
                value={printerBarName}
                onChange={(e) => setPrinterBarName(e.target.value)}
                options={printerOptions}
              />
              <div style={{ fontSize: '11px', color: 'var(--text-muted)', marginTop: '3px' }}>
                Para separar automáticamente tickets de bebidas de los de cocina.
              </div>
            </div>

            {/* Ancho de papel */}
            <div>
              <label style={{ display: 'block', fontSize: 'var(--font-xs)', fontWeight: 600, marginBottom: '4px' }}>
                Formato y Ancho de Papel Térmico
              </label>
              <div style={{ display: 'flex', gap: '10px' }}>
                <button
                  type="button"
                  onClick={() => setPaperWidth('80mm')}
                  style={{
                    flex: 1,
                    padding: '8px 12px',
                    borderRadius: 'var(--radius-sm)',
                    border: paperWidth === '80mm' ? '2px solid var(--accent-primary)' : '1px solid var(--border-color)',
                    background: paperWidth === '80mm' ? 'rgba(99, 102, 241, 0.12)' : 'var(--bg-primary)',
                    color: paperWidth === '80mm' ? 'var(--accent-primary)' : 'var(--text-secondary)',
                    fontWeight: 700,
                    fontSize: '12px',
                    cursor: 'pointer'
                  }}
                >
                  80 mm (Estándar POS)
                </button>
                <button
                  type="button"
                  onClick={() => setPaperWidth('58mm')}
                  style={{
                    flex: 1,
                    padding: '8px 12px',
                    borderRadius: 'var(--radius-sm)',
                    border: paperWidth === '58mm' ? '2px solid var(--accent-primary)' : '1px solid var(--border-color)',
                    background: paperWidth === '58mm' ? 'rgba(99, 102, 241, 0.12)' : 'var(--bg-primary)',
                    color: paperWidth === '58mm' ? 'var(--accent-primary)' : 'var(--text-secondary)',
                    fontWeight: 700,
                    fontSize: '12px',
                    cursor: 'pointer'
                  }}
                >
                  58 mm (Compacta)
                </button>
              </div>
            </div>

          </div>
        </Card>

        {/* AUTOMATIZACIÓN & AUTO-IMPRESIÓN */}
        <Card style={{ padding: '18px', background: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}>
          <h3 style={{ fontSize: '15px', fontWeight: 800, margin: '0 0 14px 0', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Sparkles size={17} color="var(--accent-secondary)" />
            Automatizaciones & Auto-Impresión Remota
          </h3>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
            
            {/* Switch 1: Impresión Silenciosa */}
            <label style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={enableSilentPrinting}
                onChange={(e) => setEnableSilentPrinting(e.target.checked)}
                style={{ accentColor: 'var(--accent-success)', width: '18px', height: '18px', marginTop: '2px', cursor: 'pointer' }}
              />
              <div>
                <strong style={{ fontSize: '13px' }}>Habilitar Impresión Silenciosa Directa (ESC/POS)</strong>
                <div style={{ fontSize: '11.5px', color: 'var(--text-muted)' }}>
                  Envía el ticket instantáneamente a la impresora térmica sin abrir cuadros de diálogo ni ventanas del navegador.
                </div>
              </div>
            </label>

            {/* Switch 2: Auto-imprimir comanda */}
            <label style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={autoPrintKitchenTickets}
                onChange={(e) => setAutoPrintKitchenTickets(e.target.checked)}
                style={{ accentColor: 'var(--accent-success)', width: '18px', height: '18px', marginTop: '2px', cursor: 'pointer' }}
              />
              <div>
                <strong style={{ fontSize: '13px' }}>Auto-imprimir comandas enviadas desde celulares de meseros</strong>
                <div style={{ fontSize: '11.5px', color: 'var(--text-muted)' }}>
                  Cuando un mesero presione "Enviar a Cocina" desde su teléfono, la comanda saldrá expulsada automáticamente en esta estación.
                </div>
              </div>
            </label>

            {/* Switch 3: Auto-imprimir factura */}
            <label style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={autoPrintInvoices}
                onChange={(e) => setAutoPrintInvoices(e.target.checked)}
                style={{ accentColor: 'var(--accent-success)', width: '18px', height: '18px', marginTop: '2px', cursor: 'pointer' }}
              />
              <div>
                <strong style={{ fontSize: '13px' }}>Auto-imprimir factura de venta al cobrar orden</strong>
                <div style={{ fontSize: '11.5px', color: 'var(--text-muted)' }}>
                  Imprime el ticket fiscal/recibo automáticamente al registrar el pago en la caja.
                </div>
              </div>
            </label>

            {/* Switch 4: Gaveta monedero */}
            <label style={{ display: 'flex', alignItems: 'flex-start', gap: '10px', cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={openDrawerOnPayment}
                onChange={(e) => setOpenDrawerOnPayment(e.target.checked)}
                style={{ accentColor: 'var(--accent-success)', width: '18px', height: '18px', marginTop: '2px', cursor: 'pointer' }}
              />
              <div>
                <strong style={{ fontSize: '13px' }}>Abrir cajón monedero automáticamente al cobrar</strong>
                <div style={{ fontSize: '11.5px', color: 'var(--text-muted)' }}>
                  Envía el pulso ESC/POS al puerto RJ11 de la impresora para expulsar el cajón de dinero.
                </div>
              </div>
            </label>

          </div>
        </Card>

      </div>

      {/* CENTRO DE PRUEBAS & DIAGNÓSTICO */}
      <Card style={{ padding: '18px', background: 'var(--bg-secondary)', border: '1px solid var(--border-color)', marginBottom: '20px' }}>
        <h3 style={{ fontSize: '15px', fontWeight: 800, margin: '0 0 6px 0', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Printer size={17} color="var(--accent-primary)" />
          Centro de Pruebas & Diagnóstico en Tiempo Real
        </h3>
        <p style={{ fontSize: '12px', color: 'var(--text-muted)', margin: '0 0 14px 0' }}>
          Prueba el corte de papel, compatibilidad de acentos (á, é, í, ó, ú, ñ) y la apertura de gaveta en 1 solo clic.
        </p>

        <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
          <Button
            type="button"
            variant="secondary"
            icon={<UtensilsCrossed size={15} />}
            onClick={handleTestKitchen}
            disabled={testingKitchen || bridgeStatus !== 'online'}
          >
            {testingKitchen ? 'Imprimiendo...' : '🍳 Probar Ticket en Cocina'}
          </Button>

          <Button
            type="button"
            variant="secondary"
            icon={<Receipt size={15} />}
            onClick={handleTestReceipt}
            disabled={testingReceipt || bridgeStatus !== 'online'}
          >
            {testingReceipt ? 'Imprimiendo...' : '🧾 Probar Factura en Caja'}
          </Button>

          <Button
            type="button"
            variant="secondary"
            icon={<DollarSign size={15} />}
            onClick={handleTestDrawer}
            disabled={testingDrawer || bridgeStatus !== 'online'}
          >
            {testingDrawer ? 'Enviando pulso...' : '💵 Probar Apertura de Gaveta'}
          </Button>
        </div>
      </Card>

      {/* PAQUETE DE DESCARGAS Y ASISTENCIA */}
      <Card style={{ padding: '18px', background: 'var(--bg-elevated)', border: '1px solid var(--border-color)' }}>
        <h3 style={{ fontSize: '15px', fontWeight: 800, margin: '0 0 10px 0', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Download size={17} color="var(--accent-primary)" />
          Paquetes de Instalación y Scripts para el Print Bridge
        </h3>
        
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: '12px', marginTop: '10px' }}>
          
          <div style={{ padding: '12px', borderRadius: '8px', background: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}>
            <div style={{ fontWeight: 700, fontSize: '13px' }}>1. Instalador Oficial Node.js</div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)', margin: '4px 0 8px 0' }}>
              Motor de ejecución obligatorio para el servidor de impresión.
            </div>
            <Button size="sm" variant="secondary" onClick={downloadNodeInstaller} style={{ width: '100%' }}>
              Descargar Node.js LTS (.msi)
            </Button>
          </div>

          <div style={{ padding: '12px', borderRadius: '8px', background: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}>
            <div style={{ fontWeight: 700, fontSize: '13px' }}>2. Lanzador de Print Bridge</div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)', margin: '4px 0 8px 0' }}>
              Inicia el servidor en consola y verifica Node.js automáticamente.
            </div>
            <Button size="sm" variant="secondary" onClick={downloadStarterBat} style={{ width: '100%' }}>
              Descargar iniciar-bridge.bat
            </Button>
          </div>

          <div style={{ padding: '12px', borderRadius: '8px', background: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}>
            <div style={{ fontWeight: 700, fontSize: '13px' }}>3. Instalador Permanente</div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)', margin: '4px 0 8px 0' }}>
              Registra el servicio para iniciar siempre en segundo plano con Windows.
            </div>
            <Button size="sm" variant="secondary" onClick={downloadInstallerBat} style={{ width: '100%' }}>
              Descargar instalar-servicio.bat
            </Button>
          </div>

          <div style={{ padding: '12px', borderRadius: '8px', background: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}>
            <div style={{ fontWeight: 700, fontSize: '13px' }}>4. Desinstalador Limpio</div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)', margin: '4px 0 8px 0' }}>
              Detiene procesos y elimina el auto-inicio de Windows.
            </div>
            <Button size="sm" variant="danger" onClick={downloadUninstallerBat} style={{ width: '100%' }}>
              Descargar desinstalador (.bat)
            </Button>
          </div>

        </div>
      </Card>

    </div>
  );
};
